### ISSUE TITLE
Weird virus detection

### ISSUE THREAD

**Issue by realhumii** [PacketDeveloper/Website#2]
Whenever I download the client, it says that it is a virus. I resume the download and Windows Defender detects it as a trojan. I've disabled real-time protection and everything but it won't download. Any support?

![packetissue](https://user-images.githubusercontent.com/118684869/202918009-3f1e8f02-9eb9-425d-b3b8-86cd304668c6.png)

**Comment by PacketDeveloper** [comment]
click show all downloads then allow file
it false flags antiviruses because of dll injection

**Comment by realhumii** [comment]
i got it fixed already but thank you so much. cool client btw

**Comment by Humii5592** [comment]
ok so i can now use the client perfectly fine its just that killaura doesnt exactly work for me and i dont know why.

**Comment by Humii5592** [comment]
hi so it takes around an hour or more for killaura to work

**Comment by shelldumbkid** [comment]
i cant open my packet client it just doesnt show up

**Comment by Humii5592** [comment]
nice custom font on your website. how'd you do that? i need custom fonts for my website too

**Comment by Dream23322** [comment]
L

**Comment by ElectroDaze** [comment]
L
